### ISSUE TITLE
Add German translation

### ISSUE THREAD

**Issue by bwl21** [cdsmith-umn/pastespecial#12]
I would volunteer to provide German translations. How an I do this?

**Comment by jinhofer** [comment]
That would be great! Are you able to fork my repository and work from a terminal?

**Comment by bwl21** [comment]
Of course, i can fork your repository. Why do I need to work from a terminal?

**Comment by jinhofer** [comment]
I'm not sure if you NEED to work from a terminal; that's just how I do all of my work. Would you be able to fork my repository, add a new directory/file:
lang/de/atto_pastespecial.php
that contains the appropriate translations, and then submit a pull request?

**Comment by bwl21** [comment]
ok, I will do that. I am using IntelliJ Idea. I will do it tomorrow.

**Comment by jinhofer** [comment]
Alright, I merged your pull request and tested it. I saw no issues and the proper language strings appear to be present! I've added it to the master branch and will include it in the next release. I'll close this ticket when I next release.

**Comment by jinhofer** [comment]
I have updated the version with Moodle, thanks for your help!

**Comment by jinhofer** [comment]
I have updated some language strings and added others to improve the usability of this plugin. Would you be able to update/add the associated German strings?

These are the strings added and changed:
https://github.com/jinhofer/pastespecial/commit/106fc7c5ae5c1233b8cb971bc1662a38f65bcd0f#diff-b3b9d0f127b5f724e048b55cebd415c5

**Comment by bwl21** [comment]
Sure, I will look at it this weekend.

**Comment by jinhofer** [comment]
Thank you for adding the translation! This will be included in the next update.
